apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
metadata:
  labels:
    istio-injection: enabled
resources:
  - ../../base

patches:
  - path: patches/api-svc.yaml
    target:
      kind: Service
      name: api
  - path: patches/restrict-developer-permissions.yaml
    target:
      kind: ClusterRole
      name: developer-base
