apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
  - ../../base

patches:
  - path: patches/api-svc.yaml
  - path: patches/restrict-developer-permissions.yaml

generators:
- ./loki/generator.yaml

configurations:
  - kustomizeconfig.yaml
