apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: istio-cni
name: cni
releaseName: istio-cni
repo: https://istio-release.storage.googleapis.com/charts
version: 1.22.3
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: istiod
name: istiod
releaseName: istiod
repo: https://istio-release.storage.googleapis.com/charts
version: 1.22.3
values:
  global:
    platform: microk8s
    istioNamespace: istio-system
  sidecarInjectorWebhook:
    enableNamespacesByDefault: true
  proxy:
    caAddress: istiod.istio-system.svc:15012
  meshConfig:
    enablePrometheusMerge: true
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*outlier_detection.*"
          - ".*upstream_rq.*"
          - ".*upstream_cx.*"
          - ".*version.*"
          - ".*cluster.*"
        inclusionPrefixes:
          - "http.outbound"
          - "http.inbound"
          - "tcp."
      extraStatTags:
        - destination_cluster
        - source_cluster
  pilot:
    replicaCount: 1
    autoscaleEnabled: false
    holdApplicationUntilProxyStarts: true
  telemetry:
    v2:
      prometheus:
        enabled: true
        configOverride:
          metrics:
            - name: requests_total
              dimensions:
                destination_cluster: "node.metadata['cluster_id']"
                source_cluster: "upstream_peer.cluster_id"
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kiali
name: kiali-server
releaseName: kiali
repo: https://kiali.org/helm-charts
values:
  auth:
    strategy: anonymous
  deployment:
    view_only_mode: true
  external_services:
    prometheus:
      url: http://loki-stack-prometheus-server.monitoring.svc.cluster.local:80
    grafana:
      enabled: true
    tracing:
      enabled: true
      internal_url: "http://jaeger.monitoring.svc.cluster.local:16686"
    istio:
      root_namespace: istio-system
    istio_namespace: istio-system
