apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: istio-base
name: base
releaseName: istio-base
repo: https://istio-release.storage.googleapis.com/charts
version: 1.22.3
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: istio-cni
name: cni
releaseName: istio-cni
repo: https://istio-release.storage.googleapis.com/charts
version: 1.22.3
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: istiod
name: istiod
releaseName: istiod
repo: https://istio-release.storage.googleapis.com/charts
version: 1.22.3
values:
  pilot:
    replicaCount: 1
    autoscaleEnabled: false
    holdApplicationUntilProxyStarts: true
  meshConfig:
    enablePrometheusMerge: true
    defaultConfig:
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*outlier_detection.*"
          - ".*upstream_rq.*"
          - ".*upstream_cx.*"
          - ".*version.*"
          - ".*cluster.*"
        inclusionPrefixes:
          - "http.outbound"
          - "http.inbound"
          - "tcp."
      extraStatTags:
        - destination_cluster
        - source_cluster
  telemetry:
    v2:
      prometheus:
        enabled: true
        configOverride:
          metrics:
            - name: requests_total
              dimensions:
                destination_cluster: "node.metadata['CLUSTER_ID']"
                source_cluster: "upstream_peer.cluster_id"
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: prometheus
name: prometheus
releaseName: prometheus
repo: https://prometheus-community.github.io/helm-charts
version: 25.1.0
namespace: istio-system
values:
  extraScrapeConfigs: |
    - job_name: 'istio-mesh'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names: ['istio-system']
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: istio-telemetry;prometheus
    - job_name: 'envoy-stats'
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          action: keep
          regex: '.*-envoy-prom'
    retention: 7d
    persistentVolume:
      enabled: true
      size: 5Gi
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: true
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kiali
name: kiali-server
releaseName: kiali
repo: https://kiali.org/helm-charts
values:
  auth:
    strategy: "anonymous"
  deployment:
    view_only_mode: true
  external_services:
    prometheus:
      url: http://prometheus-server.istio-system:80
      custom_metrics_url:  http://prometheus-server.istio-system:80
    grafana:
      enabled: false
