apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - generator.yaml

configMapGenerator:
  - name: namespace-labeler
    literals:
      - LABEL_NAMESPACE=prod
      - LABEL_KEY=istio-injection
      - LABEL_VALUE=enabled
