apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- statefulset.yaml
- service.yaml
secretGenerator:
- name: mongodb-secrets
  literals:
  - root-username=admin
  - root-password=change-me-in-overlays
