apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.21
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          ports:
            - containerPort: 5775
              protocol: UDP
              name: agent-compact
            - containerPort: 6831
              protocol: UDP
              name: agent-thrift
            - containerPort: 6832
              protocol: UDP
              name: agent-binary
            - containerPort: 5778
              protocol: TCP
              name: configs
            - containerPort: 16686
              protocol: TCP
              name: query
            - containerPort: 14268
              protocol: TCP
              name: collector-http
            - containerPort: 14250
              protocol: TCP
              name: collector-grpc
            - containerPort: 9411
              protocol: TCP
              name: zipkin
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 1
            periodSeconds: 5
