apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: istio-base
name: base
releaseName: istio-base
repo: https://istio-release.storage.googleapis.com/charts
version: 1.22.3
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: istio-cni
name: cni
releaseName: istio-cni
repo: https://istio-release.storage.googleapis.com/charts
version: 1.22.3
values:
  profile: ambient
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: istiod
name: istiod
releaseName: istiod
repo: https://istio-release.storage.googleapis.com/charts
version: 1.22.3
values:
  profile: ambient
  pilot:
    replicaCount: 1
    autoscaleEnabled: false
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "1"
      memory: "512Mi"
    enableProtocolSniffingForOutbound: false
    enableProtocolSniffingForInbound: false
    holdApplicationUntilProxyStarts: true
  meshConfig:
    enablePrometheusMerge: true
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ztunnel
name: ztunnel
releaseName: ztunnel
repo: https://istio-release.storage.googleapis.com/charts
version: 1.22.3
values:
  pilot:
    initContainers:
    - name: wait-for-cert
      image: busybox:1.28
      command: ['sh', '-c', 'until kubectl get configmap istio-ca-root-cert -n istio-system; do echo waiting for configmap; sleep 2; done']
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  readinessProbe:
    httpGet:
      path: /healthz/ready
      port: 15021
    initialDelaySeconds: 5
    periodSeconds: 5
  # Add startup probe to handle slow initial connections
  startupProbe:
    httpGet:
      path: /healthz/ready
      port: 15021
    failureThreshold: 30
    periodSeconds: 5
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kiali
name: kiali-server
releaseName: kiali
repo: https://kiali.org/helm-charts
values:
  auth:
    strategy: "anonymous" # No authentication for Kiali UI, this is for demo purposes yo!
  deployment:
    view_only_mode: true
  external_services:
    istio:
      enabled: true
    prometheus:
      enabled: true
      url: "http://loki-stack-prometheus-server.prod.svc.cluster.local:9090"
