apiVersion: v1
kind: Service
metadata:
  name: eventstore
  labels:
    app: eventstore
spec:
  type: ClusterIP
  selector:
    app: eventstore
  ports:
    - name: tcp
      port: 1113
      targetPort: 1113
    - name: http
      port: 2113
      targetPort: 2113
