apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: grafana
name: grafana
repo: https://grafana.github.io/helm-charts
version: 7.3.7
releaseName: grafana
values:
  adminUser: admin
  adminPassword: admin # can be hardcoded for initial setup
  persistence:
    enabled: true
    size: 2Gi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki.default.svc.cluster.local:3100  # Matches your Loki release
        access: proxy
        isDefault: true
        jsonData:
          maxLines: 1000
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      loki-overview:
        gnetId: 13639  # Popular Loki dashboard from Grafana.com
        revision: 1
        datasource: Loki
